version: "3"

services:
  api:
    build:
      context: ./backend
    image: rahsaf90/aegis:backend-latest
      #registry.digitalocean.com/zi-impact-docker/zi-dom-api:latest
    command: gunicorn ZeroImpact.wsgi:application --bind 0.0.0.0:8413
    volumes:
      - static_volume:/home/zer0g/api/staticfiles
      - media_volume:/home/zer0g/api/mediafiles
    expose:
      - 8413
    env_file:
      - ./.env.prod.api
    # depends_on:
    #   - db
  # db:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod.db
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

  nuxt:
    build:
      context: ./frontend
      args:
        - NUXT_API_URL=https://prisms-lte.zer0g.com:8443/api/
    image:  rahsaf90/aegis:frontend-latest
      #registry.digitalocean.com/zi-impact-docker/zi-dom-web:latest
    env_file:
      - ./.env.prod.frontend
    expose:
      - 3000

  proxy:
    build: ./proxy
    image: rahsaf90/aegis:proxy-latest
      # registry.digitalocean.com/zi-impact-docker/zi-dom-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # networks:
    #  - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # networks:
    #  - proxy-tier
    depends_on:
      - proxy
volumes:
  certs:
  vhost.d:
  html:
#  postgres_data:
  static_volume:
  media_volume:
# networks:
#  proxy-tier:
